<?php

return [
    'roles' => [
        'superadmin' => 'Superadmin',
        'hr_admin' => 'HR Admin',
        'payroll_admin' => 'Payroll Admin',
        'finance_admin' => 'Finance Admin',
        'manager' => 'Manager',
        'employee' => 'Employee',
    ],

    'groups' => [
        'Umum' => [
            'dashboard.view' => 'Lihat dashboard',
        ],
        'Karyawan & Organisasi' => [
            'employees.view' => 'Lihat karyawan',
            'employees.create' => 'Tambah karyawan',
            'employees.update' => 'Ubah karyawan',
            'employees.delete' => 'Nonaktifkan karyawan',
            'employees.approvers.manage' => 'Atur approver karyawan',
            'organization.manage' => 'Kelola departemen',
        ],
        'Presensi & Jadwal' => [
            'attendance.view' => 'Lihat presensi',
            'attendance.manage' => 'Ubah rekap presensi',
            'schedule.view' => 'Lihat jadwal kerja',
            'schedule.manage' => 'Kelola jadwal kerja',
            'schedule.master.manage' => 'Kelola shift, template, dan hari libur',
            'attendance.settings.manage' => 'Kelola pengaturan presensi',
        ],
        'Cuti & Approval' => [
            'leaves.view' => 'Lihat cuti',
            'leaves.create' => 'Buat cuti admin',
            'leaves.delete' => 'Hapus cuti',
            'leave.settings.manage' => 'Kelola kebijakan dan saldo cuti',
            'approvals.view' => 'Lihat persetujuan',
            'approvals.action' => 'Approve/reject pengajuan',
            'approvals.rules.manage' => 'Kelola aturan approval',
        ],
        'Anggaran & LHP' => [
            'budget.view' => 'Lihat pengajuan anggaran',
            'budget.manage' => 'Kelola pengajuan anggaran',
            'travel.reports.view' => 'Lihat LHP',
            'travel.reports.manage' => 'Kelola LHP',
            'travel.settings.manage' => 'Kelola kebijakan dan zona perjalanan',
        ],
        'Payroll, Pajak & BPJS' => [
            'payroll.master.view' => 'Lihat master payroll',
            'payroll.master.manage' => 'Kelola master payroll',
            'payroll.runs.view' => 'Lihat run payroll',
            'payroll.runs.create' => 'Buat run payroll',
            'payroll.runs.update' => 'Ubah detail run payroll',
            'payroll.runs.publish' => 'Finalize/publish/lock payroll',
            'payroll.runs.delete' => 'Hapus run payroll',
            'payslips.view' => 'Lihat payslip',
            'payroll.loans.view' => 'Lihat pinjaman karyawan',
            'payroll.loans.manage' => 'Kelola pinjaman karyawan',
            'payroll.adjustments.manage' => 'Kelola adjustment payroll',
            'tax.manage' => 'Kelola pajak dan BPJS',
        ],
        'Laporan' => [
            'reports.view' => 'Lihat pusat laporan',
            'reports.attendance.view' => 'Lihat laporan absensi',
            'reports.leave.view' => 'Lihat laporan cuti',
            'reports.overtime.view' => 'Lihat laporan lembur',
            'reports.payroll.view' => 'Lihat laporan payroll',
        ],
        'Pengaturan & Keamanan' => [
            'company.manage' => 'Kelola info perusahaan',
            'security.permissions.manage' => 'Kelola role permission',
            'security.audit.view' => 'Lihat audit log',
        ],
    ],

    'defaults' => [
        'superadmin' => ['*'],
        'hr_admin' => [
            'dashboard.view',
            'employees.view', 'employees.create', 'employees.update', 'employees.delete', 'employees.approvers.manage',
            'organization.manage',
            'attendance.view', 'attendance.manage',
            'schedule.view', 'schedule.manage', 'schedule.master.manage',
            'leaves.view', 'leaves.create', 'leaves.delete', 'leave.settings.manage',
            'approvals.view', 'approvals.action', 'approvals.rules.manage',
            'reports.view', 'reports.attendance.view', 'reports.leave.view', 'reports.overtime.view',
            'company.manage', 'attendance.settings.manage',
        ],
        'payroll_admin' => [
            'dashboard.view',
            'employees.view',
            'attendance.view',
            'payroll.master.view', 'payroll.master.manage',
            'payroll.runs.view', 'payroll.runs.create', 'payroll.runs.update', 'payroll.runs.publish', 'payroll.runs.delete',
            'payslips.view', 'payroll.adjustments.manage',
            'payroll.loans.view', 'payroll.loans.manage',
            'reports.view', 'reports.payroll.view',
        ],
        'finance_admin' => [
            'dashboard.view',
            'employees.view',
            'budget.view', 'budget.manage',
            'travel.reports.view', 'travel.reports.manage', 'travel.settings.manage',
            'payroll.loans.view', 'payroll.loans.manage',
            'tax.manage',
            'reports.view', 'reports.payroll.view',
        ],
        'admin' => [
            'dashboard.view',
            'employees.view', 'employees.create', 'employees.update', 'employees.delete', 'employees.approvers.manage',
            'organization.manage',
            'attendance.view', 'attendance.manage',
            'schedule.view', 'schedule.manage', 'schedule.master.manage',
            'leaves.view', 'leaves.create', 'leaves.delete', 'leave.settings.manage',
            'approvals.view', 'approvals.action', 'approvals.rules.manage',
            'budget.view', 'budget.manage',
            'travel.reports.view', 'travel.reports.manage', 'travel.settings.manage',
            'payroll.master.view', 'payroll.master.manage',
            'payroll.runs.view', 'payroll.runs.create', 'payroll.runs.update', 'payroll.runs.publish', 'payroll.runs.delete',
            'payslips.view', 'payroll.adjustments.manage', 'payroll.loans.view', 'payroll.loans.manage',
            'tax.manage',
            'reports.view', 'reports.attendance.view', 'reports.leave.view', 'reports.overtime.view', 'reports.payroll.view',
            'company.manage', 'attendance.settings.manage',
        ],
        'manager' => [
            'dashboard.view',
            'employees.view',
            'attendance.view',
            'schedule.view',
            'leaves.view', 'leaves.create',
            'approvals.view', 'approvals.action',
            'budget.view',
            'travel.reports.view', 'travel.reports.manage',
            'reports.view', 'reports.attendance.view', 'reports.leave.view', 'reports.overtime.view',
        ],
        'employee' => [],
    ],

    'route_permissions' => [
        'admin.dashboard' => 'dashboard.view',
        'admin.employees.index' => 'employees.view',
        'admin.employees.show' => 'employees.view',
        'admin.employees.create' => 'employees.create',
        'admin.employees.store' => 'employees.create',
        'admin.employees.export' => 'employees.view',
        'admin.employees.edit' => 'employees.update',
        'admin.employees.update' => 'employees.update',
        'admin.employees.portal-link.send-all' => 'employees.update',
        'admin.employees.portal-link.send' => 'employees.update',
        'admin.employees.portal-link.whatsapp.send-all' => 'employees.update',
        'admin.employees.portal-link.whatsapp.send' => 'employees.update',
        'admin.employees.destroy' => 'employees.delete',
        'admin.employees.resign' => 'employees.delete',
        'admin.employees.process-resign' => 'employees.delete',
        'admin.employees.approvers.*' => 'employees.approvers.manage',
        'admin.departments.*' => 'organization.manage',

        'admin.attendance.*' => 'attendance.view',
        'admin.attendance-photo-archives.*' => 'attendance.manage',
        'admin.attendance-recap.index' => 'attendance.view',
        'admin.attendance-recap.employee-detail' => 'attendance.view',
        'admin.attendance-recap.update' => 'attendance.manage',
        'admin.attendance-recap.import' => 'attendance.manage',
        'admin.attendance-settings.*' => 'attendance.settings.manage',

        'admin.leaves.index' => 'leaves.view',
        'admin.leaves.show' => 'leaves.view',
        'admin.leaves.create' => 'leaves.create',
        'admin.leaves.store' => 'leaves.create',
        'admin.leaves.destroy' => 'leaves.delete',
        'admin.leave-policies.*' => 'leave.settings.manage',
        'admin.leave-balances.*' => 'leave.settings.manage',
        'admin.leave-types.*' => 'leave.settings.manage',

        'admin.schedules.index' => 'schedule.view',
        'admin.schedules.store' => 'schedule.manage',
        'admin.schedules.bulk' => 'schedule.manage',
        'admin.schedules.clear' => 'schedule.manage',
        'admin.schedules.destroy' => 'schedule.manage',
        'admin.shifts.*' => 'schedule.master.manage',
        'admin.schedule-templates.*' => 'schedule.master.manage',
        'admin.holidays.*' => 'schedule.master.manage',

        'admin.approvals.index' => 'approvals.view',
        'admin.approvals.approve' => 'approvals.action',
        'admin.approvals.reject' => 'approvals.action',
        'admin.monitor-approvals.index' => 'approvals.view',
        'admin.approval-rules.*' => 'approvals.rules.manage',

        'admin.budget-requests.index' => 'budget.view',
        'admin.budget-requests.show' => 'budget.view',
        'admin.budget-requests.destroy' => 'budget.manage',
        'admin.budget-payments.*' => 'budget.manage',
        'admin.travel-reports.index' => 'travel.reports.view',
        'admin.travel-reports.show' => 'travel.reports.view',
        'admin.travel-reports.print' => 'travel.reports.view',
        'admin.travel-reports.create' => 'travel.reports.manage',
        'admin.travel-reports.store' => 'travel.reports.manage',
        'admin.travel-reports.edit' => 'travel.reports.manage',
        'admin.travel-reports.update' => 'travel.reports.manage',
        'admin.travel-reports.destroy' => 'travel.reports.manage',
        'admin.lpj.index' => 'travel.reports.view',
        'admin.lpj.show' => 'travel.reports.view',
        'admin.lpj.export-excel' => 'travel.reports.view',
        'admin.lpj.import-excel' => 'travel.reports.manage',
        'admin.lpj.destroy' => 'travel.reports.manage',
        'admin.policies.*' => 'travel.settings.manage',
        'admin.travel-zones.*' => 'travel.settings.manage',

        'admin.company.*' => 'company.manage',

        'admin.payroll-components.index' => 'payroll.master.view',
        'admin.payroll-components.employees' => 'payroll.master.manage',
        'admin.payroll-components.*' => 'payroll.master.manage',
        'admin.employee-payrolls.index' => 'payroll.master.view',
        'admin.employee-payrolls.edit' => 'payroll.master.manage',
        'admin.employee-payrolls.*' => 'payroll.master.manage',
        'admin.payroll-runs.index' => 'payroll.runs.view',
        'admin.payroll-runs.show' => 'payroll.runs.view',
        'admin.payroll-runs.store' => 'payroll.runs.create',
        'admin.payroll-runs.update-detail' => 'payroll.runs.update',
        'admin.payroll-runs.finalize' => 'payroll.runs.publish',
        'admin.payroll-runs.publish' => 'payroll.runs.publish',
        'admin.payroll-runs.unpublish' => 'payroll.runs.publish',
        'admin.payroll-runs.lock' => 'payroll.runs.publish',
        'admin.payroll-runs.unlock' => 'payroll.runs.publish',
        'admin.payroll-runs.reopen' => 'payroll.runs.publish',
        'admin.payroll-runs.regenerate' => 'payroll.runs.update',
        'admin.payroll-runs.inject-bpjs' => 'payroll.runs.update',
        'admin.payroll-runs.destroy' => 'payroll.runs.delete',
        'admin.payslips.*' => 'payslips.view',
        'admin.loan-requests.index' => 'payroll.loans.view',
        'admin.loan-requests.show' => 'payroll.loans.view',
        'admin.loan-requests.create' => 'payroll.loans.manage',
        'admin.loan-requests.store' => 'payroll.loans.manage',
        'admin.loan-requests.edit' => 'payroll.loans.manage',
        'admin.loan-requests.update' => 'payroll.loans.manage',
        'admin.loan-requests.destroy' => 'payroll.loans.manage',
        'admin.payroll-adjustments.*' => 'payroll.adjustments.manage',
        'admin.tax.*' => 'tax.manage',

        'admin.reports.index' => 'reports.view',
        'admin.reports.attendance' => 'reports.attendance.view',
        'admin.reports.export-attendance' => 'reports.attendance.view',
        'admin.reports.leave' => 'reports.leave.view',
        'admin.reports.export-leave' => 'reports.leave.view',
        'admin.reports.overtime' => 'reports.overtime.view',
        'admin.reports.export-overtime' => 'reports.overtime.view',
        'admin.reports.payroll' => 'reports.payroll.view',
        'admin.reports.export-payroll' => 'reports.payroll.view',

        'admin.role-permissions.*' => 'security.permissions.manage',
        'admin.roles.*' => 'security.permissions.manage',
        'admin.audit-logs.*' => 'security.audit.view',
    ],
];
