<?php

return [
    'permissions' => [
        ['key' => 'employees.view', 'group' => 'Karyawan', 'name' => 'Lihat data karyawan'],
        ['key' => 'employees.manage', 'group' => 'Karyawan', 'name' => 'Kelola data karyawan'],
        ['key' => 'attendance.view', 'group' => 'Presensi', 'name' => 'Lihat presensi'],
        ['key' => 'attendance.manage', 'group' => 'Presensi', 'name' => 'Kelola presensi'],
        ['key' => 'leave.view', 'group' => 'Cuti', 'name' => 'Lihat cuti'],
        ['key' => 'leave.manage', 'group' => 'Cuti', 'name' => 'Kelola cuti'],
        ['key' => 'budget.view', 'group' => 'Anggaran', 'name' => 'Lihat anggaran dan LHP'],
        ['key' => 'budget.manage', 'group' => 'Anggaran', 'name' => 'Kelola anggaran dan LHP'],
        ['key' => 'schedule.view', 'group' => 'Jadwal', 'name' => 'Lihat jadwal kerja'],
        ['key' => 'schedule.manage', 'group' => 'Jadwal', 'name' => 'Kelola jadwal kerja'],
        ['key' => 'payroll.view', 'group' => 'Payroll', 'name' => 'Lihat payroll dan payslip'],
        ['key' => 'payroll.manage', 'group' => 'Payroll', 'name' => 'Kelola payroll'],
        ['key' => 'tax.view', 'group' => 'Pajak & BPJS', 'name' => 'Lihat pajak dan BPJS'],
        ['key' => 'tax.manage', 'group' => 'Pajak & BPJS', 'name' => 'Kelola pajak dan BPJS'],
        ['key' => 'approval.view', 'group' => 'Persetujuan', 'name' => 'Lihat persetujuan'],
        ['key' => 'approval.manage', 'group' => 'Persetujuan', 'name' => 'Kelola persetujuan'],
        ['key' => 'reports.view', 'group' => 'Laporan', 'name' => 'Lihat laporan'],
        ['key' => 'settings.manage', 'group' => 'Pengaturan', 'name' => 'Kelola pengaturan perusahaan'],
        ['key' => 'permissions.manage', 'group' => 'Keamanan', 'name' => 'Kelola role permission'],
        ['key' => 'audit.view', 'group' => 'Keamanan', 'name' => 'Lihat audit log'],
    ],

    'admin_default_permissions' => [
        'employees.view',
        'employees.manage',
        'attendance.view',
        'attendance.manage',
        'leave.view',
        'leave.manage',
        'budget.view',
        'budget.manage',
        'schedule.view',
        'schedule.manage',
        'payroll.view',
        'payroll.manage',
        'tax.view',
        'tax.manage',
        'approval.view',
        'approval.manage',
        'reports.view',
        'settings.manage',
    ],
];
